// Writes $UCI_DIR/report.md and disagreements.jsonl from labelled.jsonl and engine.jsonl: where the
// engine and the UCI PI type classifier agree on real-world fields, and the cases where they don't.
// Their labels are a model's, about 94% right on their own validation set: a disagreement is a
// case to look at, not an engine error.
//
//   node scripts/uci/run.mjs report
import { createReadStream, writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { resolve } from 'node:path';
import { compareForm, summarize, type Compared, type EngineRow, type GroupCase, type LabelledForm, type Summary } from './compare';
import { UCI_FORM_TYPES, UCI_LABELS } from './map';

const UCI_DIR = process.env.UCI_DIR || resolve(process.env.HOME || '', 'datasets/uci-webform');
const EXAMPLES = 6;
// Both sides sure and still apart: the cases most worth a look.
// Their probabilities run low: 0.8 is sure for them.
const SURE_THEM = 0.8, SURE_US = 0.8;

async function readJsonl<T>(name: string): Promise<T[]> {
  const rows: T[] = [];
  for await (const line of createInterface({ input: createReadStream(resolve(UCI_DIR, name)) })) if (line) rows.push(JSON.parse(line));
  return rows;
}

const key = (row: { job: string; form: string }) => `${row.job}/${row.form}`;
const pct = (part: number, whole: number) => whole ? `${(100 * part / whole).toFixed(1)}%` : '–';
const cell = (text: string) => text.replace(/\|/g, '\\|').replace(/\s*\n+\s*/g, ' · ').slice(0, 150);
const top = (counts: Record<string, number>, n = 3, skip?: (k: string) => boolean) =>
  Object.entries(counts).filter(([k]) => !skip?.(k)).sort((a, b) => b[1] - a[1]).slice(0, n).map(([k, v]) => `${k} ${v}`).join(', ') || '–';
// The rank of a disagreement: how sure each side was.
const strength = (c: GroupCase) => c.verdict === 'extra' ? c.confidence * (1 - c.probability) : c.verdict === 'missed' ? c.probability : c.probability * c.confidence;
// The group's field text without its name line, shortened for a table.
const clue = (c: GroupCase) => cell(c.text.split('\n').slice(2).filter(line => !/^\s*(tagName|isVisible):/.test(line)).join('\n'));

function exampleTable(cases: readonly GroupCase[]): string[] {
  if (!cases.length) return ['', '_None._'];
  return ['', '| Site | Field | Clues | Theirs | Ours |', '| --- | --- | --- | --- | --- |',
    ...cases.map(c => `| ${c.domain} | \`${cell(c.name ?? '(no name)')}\` | ${clue(c)} | ${c.labels.join(', ') || 'none'} (${c.probability.toFixed(2)}) | ${c.ours} (${c.confidence.toFixed(2)}${c.evidence ? `; ${cell(c.evidence)}` : ''}) |`)];
}

function render(summary: Summary, cases: readonly GroupCase[], meta: { forms: number; reproduced: number; failed: number }): string {
  const v = summary.verdicts;
  const comparable = (v.agree ?? 0) + (v.missed ?? 0) + (v.conflict ?? 0);
  const sure = cases.filter(c => c.verdict === 'conflict' && c.probability >= SURE_THEM && c.confidence >= SURE_US).length;
  const lines = [
    '# Engine vs. the UCI PI type classifier',
    '',
    `Generated by \`node scripts/uci/run.mjs report\` on ${new Date().toISOString().slice(0, 10)}. Their labels come from a model (SetFit, about 94% micro-F1 on their own validation set), so a disagreement is a case to review, not an engine error.`,
    '',
    `${meta.forms} English forms; their labels, rerun field by field, reproduce the dataset's stored list for ${pct(meta.reproduced, meta.forms)} of them. ${meta.failed} forms failed in the engine. Counted below: field groups the crawler saw on screen. ${summary.hidden} hidden groups and ${summary.unseen} the engine never classified (hidden inputs, buttons, broken markup) are left out.`,
    '',
    '## Verdicts',
    '',
    '| Verdict | Groups | Meaning |', '| --- | --- | --- |',
    `| agree | ${v.agree ?? 0} (${pct(v.agree ?? 0, comparable)} of compared) | our type is one their label covers |`,
    `| missed | ${v.missed ?? 0} (${pct(v.missed ?? 0, comparable)}) | they name PI we have a type for, we say unknown |`,
    `| conflict | ${v.conflict ?? 0} (${pct(v.conflict ?? 0, comparable)}) | we name another type; ${sure} with them ≥ ${SURE_THEM} and us ≥ ${SURE_US} |`,
    `| extra | ${v.extra ?? 0} | we name a PI type, they see no PI |`,
    `| out-of-scope | ${v['out-of-scope'] ?? 0} | only labels we have no type for (tax ID, government ID…) |`,
    `| none | ${v.none ?? 0} | neither side names PI |`,
    '',
    '## By their label',
    '',
    '| Label | Groups | Agree | Missed | Conflict | Our types when apart |', '| --- | --- | --- | --- | --- | --- |',
    ...Object.entries(summary.labels).sort((a, b) => b[1].total - a[1].total).map(([label, s]) =>
      `| ${label}${UCI_LABELS[label]?.length ? '' : ' (out of scope)'} | ${s.total} | ${pct(s.agree, s.total)} | ${s.missed} | ${s.conflict} | ${top(s.ours, 4, k => UCI_LABELS[label]?.includes(k) ?? false)} |`),
    '',
    '## Where we name PI and they see none',
    '',
    top(summary.extra, 12),
    '',
    '## Form types',
    '',
    '| Their form type | Forms | Agree | Our types |', '| --- | --- | --- | --- |',
    ...Object.entries(summary.forms).sort((a, b) => b[1].total - a[1].total).map(([type, s]) =>
      `| ${type} | ${s.total} | ${UCI_FORM_TYPES[type] ? `${pct(s.agree, s.agree + s.conflict)} (as ${UCI_FORM_TYPES[type]}; ${s.total - s.agree - s.conflict} with no form read)` : 'not compared'} | ${top(s.ours, 4)} |`),
    '',
    '## Examples',
    '',
    `The ${EXAMPLES} strongest of each kind; every case is in disagreements.jsonl.`,
  ];
  for (const label of Object.keys(summary.labels).filter(l => UCI_LABELS[l]?.length).sort((a, b) => summary.labels[b].total - summary.labels[a].total)) {
    for (const verdict of ['missed', 'conflict'] as const) {
      const picked = cases.filter(c => c.verdict === verdict && c.labels.includes(label)).slice(0, EXAMPLES);
      if (picked.length) lines.push('', `### ${label}: ${verdict}`, ...exampleTable(picked));
    }
  }
  lines.push('', '### Extra', ...exampleTable(cases.filter(c => c.verdict === 'extra').slice(0, EXAMPLES * 2)), '');
  return lines.join('\n');
}

const labelled = await readJsonl<LabelledForm>('labelled.jsonl');
const engine = new Map((await readJsonl<EngineRow>('engine.jsonl')).map(row => [key(row), row]));
const results: Compared[] = [];
let reproduced = 0, failed = 0;
for (const form of labelled) {
  reproduced += +(form.groups.flatMap(group => group.labels).join() === form.stored.join());
  const row = engine.get(key(form));
  if (!row || row.error) { failed++; continue; }
  results.push(compareForm(form, row));
}
const summary = summarize(results);
const cases = results.flatMap(result => result.groups)
  .filter(c => c.visible && (c.verdict === 'missed' || c.verdict === 'conflict' || c.verdict === 'extra'))
  .sort((a, b) => strength(b) - strength(a));
writeFileSync(resolve(UCI_DIR, 'disagreements.jsonl'), cases.map(c => JSON.stringify(c)).join('\n') + '\n');
writeFileSync(resolve(UCI_DIR, 'report.md'), render(summary, cases, { forms: labelled.length, reproduced, failed }));
console.log(`${results.length} forms compared, ${cases.length} disagreements -> ${resolve(UCI_DIR, 'report.md')}`);
